import { Inter } from 'next/font/google'
import NavbarDefault from './components/nav'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <NavbarDefault />
        </header>
        <main className="flex min-h-screen flex-col p-24 w-1/2 m-auto">
          {children}
        </main>
      </body>
    </html>
  )
}
